### ISSUE TITLE
MicroBit V2 error 841

### ISSUE THREAD

**Issue by dsssssssss9** [microbit-makecode-packages/OLED12864_I2C#4]
When running the following code which plots / unplots random rectangles on a 128*64 OLED connected via I2C i get error 841 appearing on the MicroBit display seemingly at random

https://makecode.microbit.org/_E7gb4wFsr6Uy

BBC MicroBit V2

Linux Ubuntu 20.04 -
Chromium Version 90.0.4430.93 (Official Build) but all browsers tried seem to exhibit the same error

**Comment by microbit-mark** [comment]
Please can you advise on this @shaoziyang?

**Comment by shaoziyang** [comment]
It works in microbit V1, I will try it in microbit V2 later.

**Comment by shaoziyang** [comment]
@dsssssssss9 @microbit-mark 
Error 841 mean **garbage collection work queue error**, makecode show this message when occur memory error. MakeCode  using new memory garbage collection algorithm after version v2, many old externsions may occur memory error.

Please use OLED12864_I2C_V2 instead, it reduces memory usage, and will not show error 841.
[https://github.com/makecode-extensions/OLED12864_I2C_V2](https://github.com/makecode-extensions/OLED12864_I2C_V2)

**Comment by dsssssssss9** [comment]
Hi

Very kind of you to take the time to look into this...

Will try v2 as you suggest over the next couple days , work permitting .

I am sorry I had not looked for a later version , I had simply replaced a v1 microbit with a v2 in a previously working project  - should have thought about it a bit more before bothering you perhaps ?

Again please accept my thanks .....

**Comment by shaoziyang** [comment]
Please feel free to send me message, I'm glad to see my software being used, and I like micro:bit.
